/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoa2.compras.vista;

/**
 *
 * @author malopez
 */
public class MainCompras extends javax.swing.JPanel {
    private NuevaCompra nuevaCompra;
    private DetalleCompra detalleCompra;
    private ConsultarInventario consultarInventario;
    private Proveedores gestionarProveedores;
    
    /**
     * Creates new form MainCompras
     */
    public MainCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoCompras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonRegistrarCompra = new javax.swing.JButton();
        botonConsultarInventario = new javax.swing.JButton();
        botonGestionarProveedores = new javax.swing.JButton();
        botonDetalleCompra = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(702, 295));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaListadoCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Factura", "Proveedor", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaListadoCompras);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 680, 170));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Listado de Compras");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        botonRegistrarCompra.setText("Registrar Compra");
        botonRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarCompraActionPerformed(evt);
            }
        });
        add(botonRegistrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        botonConsultarInventario.setText("Consultar Inventario");
        botonConsultarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarInventarioActionPerformed(evt);
            }
        });
        add(botonConsultarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        botonGestionarProveedores.setText("Gestionar Proveedores");
        botonGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarProveedoresActionPerformed(evt);
            }
        });
        add(botonGestionarProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, 30));

        botonDetalleCompra.setText("Ver Detalle Compra");
        botonDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleCompraActionPerformed(evt);
            }
        });
        add(botonDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarCompraActionPerformed
        nuevaCompra = new NuevaCompra();
        nuevaCompra.setVisible(true);
    }//GEN-LAST:event_botonRegistrarCompraActionPerformed

    private void botonGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarProveedoresActionPerformed
        gestionarProveedores = new Proveedores();
        gestionarProveedores.setVisible(true);
    }//GEN-LAST:event_botonGestionarProveedoresActionPerformed

    private void botonDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleCompraActionPerformed
        detalleCompra = new DetalleCompra();
        detalleCompra.setVisible(true);
    }//GEN-LAST:event_botonDetalleCompraActionPerformed

    private void botonConsultarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarInventarioActionPerformed
        consultarInventario = new ConsultarInventario();
        consultarInventario.setVisible(true);
    }//GEN-LAST:event_botonConsultarInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarInventario;
    private javax.swing.JButton botonDetalleCompra;
    private javax.swing.JButton botonGestionarProveedores;
    private javax.swing.JButton botonRegistrarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListadoCompras;
    // End of variables declaration//GEN-END:variables
}
