/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyecto2a.administracion.vista;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.marcos.dto.Menu;
import org.marcos.sql.MenuSql;

/**
 *
 * @author sharon
 */
public class AutorizarMenu extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarMenu
     */
    private ArrayList <Menu> menus = new ArrayList<>();
    public AutorizarMenu() {
        initComponents();
        this.inicializar();
    }
     private void inicializar(){
        this.setSize(new Dimension(500, 700));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jTableMenus.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        this.obtenerMenus();
    }
    private void obtenerMenus(){
        this.menus = MenuSql.MENU_ESTADO("CREADO");
        System.out.println(menus.size());
        DefaultTableModel tabla = (DefaultTableModel) jTableMenus.getModel();
        for(int i=0; i<this.menus.size(); i++)
        {
           tabla.addRow(new Object[]{menus.get(i).getIdMenu(), menus.get(i).getNombreMenu()});  
        }
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonAutorizarMenu = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonVerMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMenus = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        jLabel1.setText("AUTORIZAR MENÚS");

        botonAutorizarMenu.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonAutorizarMenu.setText("Autorizar Menú");
        botonAutorizarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAutorizarMenuActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonVerMenu.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonVerMenu.setText("Ver Menú");
        botonVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMenuActionPerformed(evt);
            }
        });

        jTableMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Menu"
            }
        ));
        jScrollPane2.setViewportView(jTableMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(botonVerMenu)
                            .addGap(39, 39, 39)
                            .addComponent(botonAutorizarMenu)
                            .addGap(32, 32, 32)
                            .addComponent(botonRegresar))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresar)
                    .addComponent(botonAutorizarMenu)
                    .addComponent(botonVerMenu))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAutorizarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAutorizarMenuActionPerformed
        // TODO add your handling code here:
        if(this.jTableMenus.getSelectedRow()>=0){
            Menu autorizar=this.menus.get(this.jTableMenus.getSelectedRow());
            String [] botones = { "Autorizar Menu", " Cancelar"};
            int eleccion = JOptionPane.showOptionDialog (null, " ¿Esta seguro que desea autorizar este menu?", "Autorización de menu", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]);
            if(eleccion==0)
            {
                autorizar.setEstado("ACTIVO");
                MenuSql.ACTUALIZAR(autorizar);
                JOptionPane.showConfirmDialog(this, "El menú: "+ autorizar.getNombreMenu()+" ha cambiado a ACTIVO exitosamemente.", "Menu autorizado exitosamente", JOptionPane.OK_OPTION);
                this.obtenerMenus();
            }
            
        }
        else{
            System.out.println("no ha seleccionado nada");
        }
    }//GEN-LAST:event_botonAutorizarMenuActionPerformed

    private void botonVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMenuActionPerformed
        // TODO add your handling code here:
        VerMenu ver = new VerMenu();
        ver.setVisible(true);
    }//GEN-LAST:event_botonVerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutorizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutorizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutorizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutorizarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutorizarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAutorizarMenu;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonVerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMenus;
    // End of variables declaration//GEN-END:variables
}
