/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyecto2a.administracion.vista;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.marcos.dto.Menu;
import org.marcos.sql.MenuSql;
import org.proyecto2a.administracion.controller.ControladorMenu;

/**
 *
 * @author sharon
 */
public class SeleccionarMenu extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarMenu
     */
    private ArrayList <Menu> menus = new ArrayList<>();
    public SeleccionarMenu() {
        initComponents();
        this.inicializar();
    }
     private void inicializar(){
        this.setSize(new Dimension(500, 700));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jTableMenus.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        this.obtenerMenus();
    }
      private void obtenerMenus(){
        this.menus = MenuSql.getAllMenu();
        System.out.println(menus.size());
        DefaultTableModel tabla = (DefaultTableModel) jTableMenus.getModel();
        tabla.setRowCount(0);
        for(int i=0; i<this.menus.size(); i++)
        {
           tabla.addRow(new Object[]{menus.get(i).getIdMenu(), menus.get(i).getNombreMenu()});  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonEditarMenu = new javax.swing.JButton();
        botonEliminarMenu = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonVerMenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMenus = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIONAR MENÚ");

        botonEditarMenu.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonEditarMenu.setText("Editar Menú");
        botonEditarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarMenuActionPerformed(evt);
            }
        });

        botonEliminarMenu.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonEliminarMenu.setText("Eliminar Menú");
        botonEliminarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMenuActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonVerMenu.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonVerMenu.setText("Ver Menú");
        botonVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMenuActionPerformed(evt);
            }
        });

        jTableMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Menu"
            }
        ));
        jScrollPane2.setViewportView(jTableMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonEditarMenu)
                            .addComponent(botonVerMenu))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(botonRegresar))
                            .addComponent(botonEliminarMenu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarMenu)
                    .addComponent(botonEliminarMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerMenu)
                    .addComponent(botonRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonEliminarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMenuActionPerformed
        // TODO add your handling code here:
        String[] botones = {"Eliminar Menu", " Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(null, " ¿Esta seguro que desea eliminar este menu?. Esta acción será permanente y no podrá recuperar los datos.", "Eliminar menu", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]);
        if (eleccion == 0) {
            Menu menu = this.menus.get(this.jTableMenus.getSelectedRow());
            boolean eliminado = ControladorMenu.EliminarMenu(menu.getIdMenu());
            JOptionPane.showMessageDialog(this, "El menú: fue eliminado exitosamemente.", "Menu eliminado exitosamente", JOptionPane.INFORMATION_MESSAGE);
            this.obtenerMenus();
        }
    }//GEN-LAST:event_botonEliminarMenuActionPerformed

    private void botonEditarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarMenuActionPerformed
        // TODO add your handling code here:
        EditarMenu editar = new EditarMenu();
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonEditarMenuActionPerformed

    private void botonVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMenuActionPerformed
        // TODO add your handling code here:
        Menu menu=this.menus.get(this.jTableMenus.getSelectedRow());
        VerMenu ver = new VerMenu(menu);
        ver.setVisible(true);
    }//GEN-LAST:event_botonVerMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarMenu;
    private javax.swing.JButton botonEliminarMenu;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonVerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMenus;
    // End of variables declaration//GEN-END:variables
}
