/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyecto2a.administracion.vista;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.marcos.dto.Menu;
import org.marcos.dto.Puesto;
import org.marcos.sql.PuestoSql;
import org.proyecto2a.administracion.controller.ControladorPuesto;

/**
 *
 * @author sharon
 */
public class SeleccionarPuesto extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarMenu
     */
    private ArrayList <Puesto> puestos = new ArrayList<>();
    public SeleccionarPuesto() {
        initComponents();
        this.inicializar();
    }
     private void inicializar(){
        this.setSize(new Dimension(500, 700));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jTablePuestos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        this.obtenerPuestos();
    }
      private void obtenerPuestos(){
        this.puestos = PuestoSql.getAllPuestos();
        DefaultTableModel tabla = (DefaultTableModel) jTablePuestos.getModel();
        tabla.setRowCount(0);
        for(int i=0; i<this.puestos.size(); i++)
        {
           tabla.addRow(new Object[]{puestos.get(i).getId(), puestos.get(i).getNombre()});  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonEditarPuesto = new javax.swing.JButton();
        botonEliminarPuesto = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonVerPuesto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePuestos = new javax.swing.JTable();
        botonAgregarPuesto = new javax.swing.JButton();
        botonVerPuesto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIONAR PUESTO");

        botonEditarPuesto.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonEditarPuesto.setText("Editar Puesto");
        botonEditarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPuestoActionPerformed(evt);
            }
        });

        botonEliminarPuesto.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonEliminarPuesto.setText("Eliminar Puesto");
        botonEliminarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPuestoActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonVerPuesto.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonVerPuesto.setText("Ver Puesto");
        botonVerPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPuestoActionPerformed(evt);
            }
        });

        jTablePuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Puesto"
            }
        ));
        jScrollPane2.setViewportView(jTablePuestos);

        botonAgregarPuesto.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonAgregarPuesto.setText("Agregar Puesto");
        botonAgregarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPuestoActionPerformed(evt);
            }
        });

        botonVerPuesto1.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        botonVerPuesto1.setText("Actualizar");
        botonVerPuesto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPuesto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonEditarPuesto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEliminarPuesto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVerPuesto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(botonAgregarPuesto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonVerPuesto1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPuesto)
                    .addComponent(botonVerPuesto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEditarPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminarPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonEliminarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPuestoActionPerformed
        // TODO add your handling code here:
       if(this.jTablePuestos.getSelectedRow()>=0){
        String[] botones = {"Eliminar Puesto", " Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(null, " ¿Esta seguro que desea eliminar este puesto?. Esta acción será permanente y no podrá recuperar los datos.", "Eliminar puesto", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]);
        if (eleccion == 0) {
            Puesto puesto = this.puestos.get(this.jTablePuestos.getSelectedRow());
            ControladorPuesto.ElminarPuesto(puesto);
            JOptionPane.showMessageDialog(this, "El puesto fue eliminado exitosamente.", "Puesto eliminado exitosamente", JOptionPane.INFORMATION_MESSAGE);
            this.obtenerPuestos();
        }
       }else{
           JOptionPane.showMessageDialog(this, "Seleccione un puesto de la lista para eliminar.", "Selección de puesto incorrecta", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_botonEliminarPuestoActionPerformed

    private void botonEditarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPuestoActionPerformed
        // TODO add your handling code here:
        if(this.jTablePuestos.getSelectedRow()>=0){
        Puesto puesto=this.puestos.get(this.jTablePuestos.getSelectedRow());
        EditarPuesto editar;
        editar = new EditarPuesto(puesto);
        editar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un menú de la lista para editar.", "Selección de menú incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEditarPuestoActionPerformed

    private void botonVerPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPuestoActionPerformed
        // TODO add your handling code here:
        if(this.jTablePuestos.getSelectedRow()>=0){
        Puesto puesto=this.puestos.get(this.jTablePuestos.getSelectedRow());
        VerPuesto ver = new VerPuesto(puesto);
        ver.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un menú de la lista para ver.", "Selección de menú incorrecta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonVerPuestoActionPerformed

    private void botonAgregarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPuestoActionPerformed
        CrearPuesto crear = new CrearPuesto();
        crear.setVisible(true);
    }//GEN-LAST:event_botonAgregarPuestoActionPerformed

    private void botonVerPuesto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPuesto1ActionPerformed
        // TODO add your handling code here:
        this.obtenerPuestos();
    }//GEN-LAST:event_botonVerPuesto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPuesto;
    private javax.swing.JButton botonEditarPuesto;
    private javax.swing.JButton botonEliminarPuesto;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonVerPuesto;
    private javax.swing.JButton botonVerPuesto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePuestos;
    // End of variables declaration//GEN-END:variables
}
