/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoa2.ventas.vista;

/**
 *
 * @author marcos
 */
public class AgregarPlatilloForm extends javax.swing.JFrame {
    private VisualizarDetallesPlatilloForm visualizarPlatillos;
    /**
     * Creates new form AgregarPlatilloForm
     */
    public AgregarPlatilloForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlatillosIncluidos = new javax.swing.JList<>();
        botonConsultarDetalles = new javax.swing.JButton();
        botonAgregarPlatillo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaPrecioUnitario = new javax.swing.JLabel();
        etiquetaMostrarPrecio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresoPrecioVenta = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 465));
        setPreferredSize(new java.awt.Dimension(650, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPlatillosIncluidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPlatillosIncluidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 250, 370));

        botonConsultarDetalles.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonConsultarDetalles.setText("Consultar Detalles Platillo");
        botonConsultarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultarDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 330, 40));

        botonAgregarPlatillo.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonAgregarPlatillo.setText("Agregar Platillo");
        botonAgregarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlatilloActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, 40));

        botonCancelar.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 330, 40));

        etiquetaCantidad.setText("Cantidad");
        getContentPane().add(etiquetaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        etiquetaPrecioUnitario.setText("Precio Unitario");
        getContentPane().add(etiquetaPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        etiquetaMostrarPrecio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        etiquetaMostrarPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiquetaMostrarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, 30));

        jLabel4.setText("Precio de Venta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        ingresoPrecioVenta.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        ingresoPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoPrecioVentaActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Platillos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoPrecioVentaActionPerformed

    private void botonConsultarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarDetallesActionPerformed
        // TODO add your handling code here:
        this.visualizarPlatillos = new VisualizarDetallesPlatilloForm();
        this.visualizarPlatillos.setVisible(true);
    }//GEN-LAST:event_botonConsultarDetallesActionPerformed

    private void botonAgregarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarPlatilloActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlatilloForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPlatillo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConsultarDetalles;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaMostrarPrecio;
    private javax.swing.JLabel etiquetaPrecioUnitario;
    private javax.swing.JTextField ingresoPrecioVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JList<String> listaPlatillosIncluidos;
    // End of variables declaration//GEN-END:variables
}
