/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoa2.ventas.vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import org.marcos.dto.DetalleComplementos;
import org.marcos.dto.DetalleOrden;
import org.marcos.dto.Menu;
import org.proyectoa2.ventas.controller.ManejoListaPlatillos;
import org.proyectoa2.ventas.controller.ManejoOrden;

/**
 *
 * @author marcos
 */
public class AgregarPlatilloForm extends javax.swing.JFrame {
    private VisualizarDetallesPlatilloForm visualizarPlatillos;
    private ManejoOrden manejoOrden;
    private ManejoListaPlatillos manejadorPlatillos;
    private NuevaOrdenForm nuevaOrden;
    private DetalleOrden nuevoPlatillo;
    /**
     * Creates new form AgregarPlatilloForm
     */
    public AgregarPlatilloForm() {
        initComponents();
    }
    public AgregarPlatilloForm(NuevaOrdenForm nuevaOrden, ManejoOrden manejoOrden) {
        initComponents();
        this.nuevaOrden = nuevaOrden;
        this.manejoOrden = manejoOrden;
        manejadorPlatillos = ManejoListaPlatillos.getManejador();
        DefaultListModel modelo = new DefaultListModel();
        ArrayList<Menu> platillos = manejadorPlatillos.getListaPlatillos();
        System.out.println(platillos.size());
        String tmp;
        for(Menu item : platillos){
            tmp = item.getNombreMenu();
            modelo.addElement(tmp);
        }
        this.listaPlatillosIncluidos.setModel(modelo);
        this.nuevoPlatillo = new DetalleOrden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlatillosIncluidos = new javax.swing.JList<>();
        botonConsultarDetalles = new javax.swing.JButton();
        botonAgregarPlatillo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaPrecioUnitario = new javax.swing.JLabel();
        etiquetaMostrarPrecio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresoPrecioVenta = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listacomplementos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        botonAgregarComplemento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(657, 630));
        setPreferredSize(new java.awt.Dimension(657, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPlatillosIncluidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaPlatillosIncluidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPlatillosIncluidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPlatillosIncluidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 250, 370));

        botonConsultarDetalles.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonConsultarDetalles.setText("Consultar Detalles Platillo");
        botonConsultarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultarDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 40));

        botonAgregarPlatillo.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonAgregarPlatillo.setText("Confirmar");
        botonAgregarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlatilloActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 330, 40));

        botonCancelar.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 330, 40));

        etiquetaCantidad.setText("Cantidad");
        getContentPane().add(etiquetaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        etiquetaPrecioUnitario.setText("Precio Unitario");
        getContentPane().add(etiquetaPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        etiquetaMostrarPrecio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        etiquetaMostrarPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiquetaMostrarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 30));

        jLabel4.setText("Precio de Venta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        ingresoPrecioVenta.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        ingresoPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoPrecioVentaActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 210, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Platillos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        listacomplementos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listacomplementos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 250, 130));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Complementos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        botonAgregarComplemento.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        botonAgregarComplemento.setText("Agregar Complemento");
        botonAgregarComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarComplementoActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 40));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Agregar Platillo a la Orden");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoPrecioVentaActionPerformed

    private void botonConsultarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarDetallesActionPerformed

        // TODO add your handling code here:
        if(listaPlatillosIncluidos.getSelectedIndex() >= 0){
        
            this.visualizarPlatillos = new VisualizarDetallesPlatilloForm(manejadorPlatillos.getPlatillo(listaPlatillosIncluidos.getSelectedIndex()));
            this.visualizarPlatillos.setVisible(true);
        }
    }//GEN-LAST:event_botonConsultarDetallesActionPerformed

    private void botonAgregarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarPlatilloActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void listaPlatillosIncluidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPlatillosIncluidosMouseClicked
        // TODO add your handling code here:
        if(listaPlatillosIncluidos.getSelectedIndex() >= 0){
        
            this.etiquetaMostrarPrecio.setText(" Q." +  Double.toString(manejadorPlatillos.getPlatillo(listaPlatillosIncluidos.getSelectedIndex()).getPrecio()));
            this.ingresoPrecioVenta.setText(Double.toString(manejadorPlatillos.getPlatillo(listaPlatillosIncluidos.getSelectedIndex()).getPrecio()));
        }
    }//GEN-LAST:event_listaPlatillosIncluidosMouseClicked

    private void botonAgregarComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarComplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlatilloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlatilloForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarComplemento;
    private javax.swing.JButton botonAgregarPlatillo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConsultarDetalles;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaMostrarPrecio;
    private javax.swing.JLabel etiquetaPrecioUnitario;
    private javax.swing.JTextField ingresoPrecioVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JList<String> listaPlatillosIncluidos;
    private javax.swing.JList<String> listacomplementos;
    // End of variables declaration//GEN-END:variables

    public void actualizarComplementos(){
        String tmp;
        
        DefaultListModel modelo = new DefaultListModel();
        for(DetalleComplementos item : nuevoPlatillo.getListaComplementos()){
            tmp = item.getInventario().getNombre() +  " || Cantidad: " + item.getCantidad();
            modelo.addElement(tmp);
        }
        listacomplementos.setModel(modelo);
    }
}
