/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoa2.ventas.vista;

/**
 *
 * @author marcos
 */
public class MainVentas extends javax.swing.JPanel {
    private NuevaOrdenForm nuevaOrdenFormulario;
    private AtenderOrdenForm atenderOrden;
    private CobrarOrdenForm cobrarOrden;
    private CobrarSaldoForm cobrarSaldo;
    /**
     * Creates new form MainVentas
     */
    public MainVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaColaOrdenes = new javax.swing.JTable();
        etiquetaColaOrdenes = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonNuevaOrden = new javax.swing.JButton();
        cancelarOrdenBoton = new javax.swing.JButton();
        editarOrdenBoton = new javax.swing.JButton();
        atenderOrdenBoton = new javax.swing.JButton();
        botonCobrarOrden = new javax.swing.JButton();
        etiquetaOpciones = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1080, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1080, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaColaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Orden", "Cliente", "Hora"
            }
        ));
        jScrollPane2.setViewportView(tablaColaOrdenes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 77, 600, 570));

        etiquetaColaOrdenes.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        etiquetaColaOrdenes.setText("Cola de Ordenes");
        add(etiquetaColaOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 10, 640));

        botonNuevaOrden.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botonNuevaOrden.setText("Registrar Nueva Orden");
        botonNuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaOrdenActionPerformed(evt);
            }
        });
        add(botonNuevaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 380, 50));

        cancelarOrdenBoton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cancelarOrdenBoton.setText("Cancelar Orden Seleccionada");
        add(cancelarOrdenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 380, 50));

        editarOrdenBoton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        editarOrdenBoton.setText("Editar Orden");
        editarOrdenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarOrdenBotonActionPerformed(evt);
            }
        });
        add(editarOrdenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 380, 50));

        atenderOrdenBoton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        atenderOrdenBoton.setText("Atender Orden");
        atenderOrdenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderOrdenBotonActionPerformed(evt);
            }
        });
        add(atenderOrdenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 380, 50));

        botonCobrarOrden.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botonCobrarOrden.setText("Cobrar Orden Seleccionada");
        botonCobrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarOrdenActionPerformed(evt);
            }
        });
        add(botonCobrarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 380, 50));

        etiquetaOpciones.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        etiquetaOpciones.setText("Opciones");
        add(etiquetaOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setText("Cancelar Saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 380, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaOrdenActionPerformed
        // TODO add your handling code here:
        nuevaOrdenFormulario = new NuevaOrdenForm("Nueva Orden");
        nuevaOrdenFormulario.setVisible(true);
    }//GEN-LAST:event_botonNuevaOrdenActionPerformed

    private void editarOrdenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarOrdenBotonActionPerformed
        // TODO add your handling code here:
        nuevaOrdenFormulario = new NuevaOrdenForm("Editar Orden");
        nuevaOrdenFormulario.setVisible(true);
    }//GEN-LAST:event_editarOrdenBotonActionPerformed

    private void atenderOrdenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderOrdenBotonActionPerformed
        // TODO add your handling code here:
        this.atenderOrden = new AtenderOrdenForm();
        this.atenderOrden.setVisible(true);
        
    }//GEN-LAST:event_atenderOrdenBotonActionPerformed

    private void botonCobrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarOrdenActionPerformed
        // TODO add your handling code here:
        this.cobrarOrden = new CobrarOrdenForm();
        this.cobrarOrden.setVisible(true);
    }//GEN-LAST:event_botonCobrarOrdenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.cobrarSaldo = new CobrarSaldoForm();
        this.cobrarSaldo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atenderOrdenBoton;
    private javax.swing.JButton botonCobrarOrden;
    private javax.swing.JButton botonNuevaOrden;
    private javax.swing.JButton cancelarOrdenBoton;
    private javax.swing.JButton editarOrdenBoton;
    private javax.swing.JLabel etiquetaColaOrdenes;
    private javax.swing.JLabel etiquetaOpciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaColaOrdenes;
    // End of variables declaration//GEN-END:variables
}
