/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.proyectoa2.ventas.vista;

/**
 *
 * @author marcos
 */
public class NuevaOrdenForm extends javax.swing.JFrame {
    private AgregarPlatilloForm agregarPlatillo;
    private AgregarClienteForm agregarCliente;
    /**
     * Creates new form NuevaOrdenForm
     */
    public NuevaOrdenForm() {
        initComponents();
    }
    public NuevaOrdenForm(String titulo) {
        initComponents();
        this.etiquetaTitulo.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        etiquetaSeleccionarCliente = new javax.swing.JLabel();
        botonAgregarPlatillo = new javax.swing.JButton();
        botonConfirmarOrden = new javax.swing.JButton();
        botonCancelarOrden = new javax.swing.JButton();
        listaSeleccionCliente = new javax.swing.JComboBox<>();
        etiquetaTotal = new javax.swing.JLabel();
        etiquetaTotalOrden = new javax.swing.JLabel();
        botonEliminarPlatillo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        etiquetaTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarCliente = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 340, 570));

        etiquetaSeleccionarCliente.setText("Seleccionar Cliente");
        getContentPane().add(etiquetaSeleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        botonAgregarPlatillo.setText("Agregar Platillo");
        botonAgregarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlatilloActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 480, -1));

        botonConfirmarOrden.setText("Confirmar Orden");
        getContentPane().add(botonConfirmarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 480, -1));

        botonCancelarOrden.setText("Cancelar Orden");
        getContentPane().add(botonCancelarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 480, -1));

        listaSeleccionCliente.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        listaSeleccionCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(listaSeleccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 560, 30));

        etiquetaTotal.setText("Total");
        getContentPane().add(etiquetaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        etiquetaTotalOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiquetaTotalOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 510, 40));

        botonEliminarPlatillo.setText("Eliminar Platillo");
        getContentPane().add(botonEliminarPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 480, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 610, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 620, 10));

        etiquetaTitulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        etiquetaTitulo.setText("Nueva Orden");
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Platillos de la orden");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        botonAgregarCliente.setText("Agregar Cliente");
        botonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 183, 540, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlatilloActionPerformed
        // TODO add your handling code here:
        this.agregarPlatillo = new AgregarPlatilloForm();
        this.agregarPlatillo.setVisible(true);
    }//GEN-LAST:event_botonAgregarPlatilloActionPerformed

    private void botonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarClienteActionPerformed
        // TODO add your handling code here:
        agregarCliente = new AgregarClienteForm();
        agregarCliente.setVisible(true);
    }//GEN-LAST:event_botonAgregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaOrdenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaOrdenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaOrdenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaOrdenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaOrdenForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCliente;
    private javax.swing.JButton botonAgregarPlatillo;
    private javax.swing.JButton botonCancelarOrden;
    private javax.swing.JButton botonConfirmarOrden;
    private javax.swing.JButton botonEliminarPlatillo;
    private javax.swing.JLabel etiquetaSeleccionarCliente;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JLabel etiquetaTotalOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listaSeleccionCliente;
    // End of variables declaration//GEN-END:variables
}
